import {mkdir,cp,rm,readdir,stat,writeFile} from 'node:fs/promises';import {execFileSync} from 'node:child_process';
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});for(const file of ['index.html','src','assets'])await cp(file,`dist/${file}`,{recursive:true});
let bytes=0,files=0;async function walk(dir){for(const e of await readdir(dir,{withFileTypes:true})){const p=`${dir}/${e.name}`;if(e.isDirectory())await walk(p);else{bytes+=(await stat(p)).size;files++;}}}await walk('dist');
await mkdir('submission',{recursive:true});execFileSync('python3',['-c',"import zipfile,pathlib\nwith zipfile.ZipFile('submission/ricochet-foundry-crazygames.zip','w',zipfile.ZIP_DEFLATED) as z:\n for p in pathlib.Path('dist').rglob('*'):\n  if p.is_file():z.write(p,p.relative_to('dist'))"]);
const report={version:'1.0.0',entry:'index.html',files,uncompressedBytes:bytes,zipBytes:(await stat('submission/ricochet-foundry-crazygames.zip')).size,supportsMobile:true,orientation:'both',sdkVersion:3,launch:'Basic',ads:false,externalDependencies:['https://sdk.crazygames.com/crazygames-sdk-v3.js'],note:'SDK downloads separately. Game works without it. Browser/portal QA details in docs/VERIFICATION.md.'};await writeFile('submission/build-report.json',JSON.stringify(report,null,2));console.log(report);
// Self-contained review build: double-click this HTML without running a server.
const {readFile}=await import('node:fs/promises');const {Script}=await import('node:vm');
let bundled='';for(const file of ['levels','engine','portal','audio','render','main']){let code=await readFile(`src/${file}.js`,'utf8');code=code.replace(/^import .*;\s*$/gm,'').replace(/^export /gm,'');bundled+=code+'\n';}
new Script(`(async()=>{${bundled}})();`);
const css=await readFile('src/style.css','utf8');let html=await readFile('index.html','utf8');html=html.replace('<link rel="stylesheet" href="./src/style.css">',`<style>${css}</style>`).replace('<link rel="icon" href="./assets/icon.svg" type="image/svg+xml">','').replace('<script type="module" src="./src/main.js"></script>',`<script>(async()=>{${bundled}})();</script>`);
await writeFile('submission/play-ricochet-foundry.html',html);console.log('Standalone review build: submission/play-ricochet-foundry.html');
